import Head from 'next/head'
import {Open_Sans} from 'next/font/google'
import {Box, DialogContentText, Typography} from '@mui/material'
import {Banner} from '@/components/Banner'
import {PaidHospitalizationBlock} from '@/components/PaidHospitalizationBlock'
import {partners, services, stepsHospitalization, timeOut, whatWeOffer1, whatWeOffer2, whatWeOffer3} from '@/config'
import {HowToBeHospitalized} from '@/components/HowToBeHospitalized'
import {PartnersBlock} from '@/components/PartnersBlock'
import {WhatWeOffer} from '@/components/WhatWeOffer'
import {FormBlock} from '@/components/FormBlock'
import {useEffect, useState} from 'react'
import {BaseModal} from '@/components/base/BaseModal'
import {ContactBlock} from '@/components/ContactBlock'

const openSans = Open_Sans({subsets: ['latin']})

export default function Home() {
    const [success, setSuccess] = useState(false)
    const [failed, setFailed] = useState(false)

    useEffect(() => {
        let timeout
        if (success || failed) {
            timeout = setTimeout(() => {
                handleClose()
            }, timeOut)
        }
        return () => {
            clearTimeout(timeout)
        }
    }, [success, failed])

    const handleClose = () => {
        setFailed(false)
        setSuccess(false)
    }

    return (
        <>
            <Head>
                <title>МСК-Групп</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/icon.png"/>
            </Head>
            <Box component="main" className={openSans.className}>
                <Banner/>
                <PaidHospitalizationBlock services={services}/>
                <HowToBeHospitalized steps={stepsHospitalization}/>
                <PartnersBlock partners={partners}/>
                <WhatWeOffer list1={whatWeOffer1} list2={whatWeOffer2} list3={whatWeOffer3}/>
                <FormBlock onSuccess={setSuccess} onFailed={setFailed}/>
                <ContactBlock/>
            </Box>

            {success && (
                <BaseModal title="Сообщение отправлено!" open={success} handleClose={handleClose}
                           color="var(--blue)">
                    <DialogContentText id="alert-dialog-description">
                        Скоро в Вами свяжется наш специалист
                    </DialogContentText>
                </BaseModal>
            )}

            {failed && (
                <BaseModal title="Ошибка сервера!" open={failed} handleClose={handleClose} color="var(--red)">
                    <DialogContentText id="alert-dialog-description">
                        Попробуйте позже
                    </DialogContentText>
                </BaseModal>
            )}

        </>
    )
}
